apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: final
  labels:
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      name: simple-webapp-mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
    spec:
      containers:
      - name: webapp
        image: 930061969411.dkr.ecr.us-east-1.amazonaws.com/project:latest
        ports:
        - containerPort: 81
        volumeMounts:
        - name: app-secret-volumes
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        envFrom:
          - secretRef:
              name: app-secret
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: app-secret